!function (window) {

  window.CONSTANT = {
    GRAVITY: 1200,
    PLAYER_JUMP_STRENGTH: 460,
    PLAYER_DECELERATION: 200,
    PLAYER_TOP_SPEED: 300,
    PLAYER_LIGHT_RADIUS: 200,
    PLAYER_END_OF_LEVEL: 1500,
    TERMINAL_VELOCITY: 690,
    MAX_HEALTH: 100,
    MAX_BATTERY: 2000,
    DAMAGE_COOLDOWN: 100,
    SLIME_SPEED: 20,
    GID: {
      SPIKE: 24,
      BATTERY: 16,
      SLIME: 21,
      STARTPOINT: 99,
      EXITPOINT: 98
    }
  };

}(window);
